---
- name: Monitor BGP peer status on Cisco IOS XR
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Retrieve BGP neighbor status
      iosxr_command:
        commands:
          - show bgp neighbors {{ bgp_peer }}
      register: bgp_status

    - name: Parse BGP neighbor status
      set_fact:
        bgp_state: "{{ bgp_status.stdout[0] | regex_search('BGP state = (\\w+)', '\\1') }}"
    
    

    - name: Print message when condition is Active
      debug:
        msg: "{{ inventory_hostname }} bgp peer status with {{bgp_peer}} is Active"
      when: bgp_state == ['Active']
    
    - name: Print message when condition is Established
      debug:
        msg: "{{ inventory_hostname }} bgp peer status with {{bgp_peer}} is Established"
      when: bgp_state == ['Established']

    - name: Print message when condition is Idle
      debug:
        msg: "{{ inventory_hostname }} bgp peer status with {{bgp_peer}} is Idle"
      when: bgp_state == ['Idle']


    
