---
- name: Monitor BGP peer status on Cisco IOS XR
  hosts: XR4router.yahoo.com
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Retrieve BGP neighbor status
      iosxr_command:
        commands:
          - show bgp neighbors 10.0.17.1
      register: bgp_status

    - name: Parse BGP neighbor status
      set_fact:
        bgp_state: "{{ bgp_status.stdout[0] | regex_search('BGP state = (\\w+)', '\\1') }}"
    
    

    - name: Print message when condition is Active
      slack:
          token: "https://hooks.slack.com/services/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"
          msg: "{{ inventory_hostname }} bgp peer status with 10.0.17.1 is Active"
          channel: "#test"
          username: "Ansible"
          
      when: bgp_state == ['Active']
    
    - name: Print message when condition is Established
      debug:
        msg: "{{ inventory_hostname }} bgp peer status with 10.0.17.1 is Established"
      when: bgp_state == ['Established']

    - name: Print message when condition is Idle
      debug:
        msg: "{{ inventory_hostname }} bgp peer status with 10.0.17.1 is Idle"
      when: bgp_state == ['Idle']


    
