---
- name: Backup Cisco IOS XR configurations locally
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show running-config on device
      iosxr_command:
        commands:
          - show running-config
      register: running_config

    - name: Get current date on control node
      delegate_to: localhost
      ansible.builtin.command: date +%Y-%m-%d
      register: current_date
      changed_when: false

    - name: Save running config to local file on control node
      delegate_to: localhost
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/home/rasty/{{ inventory_hostname }}-running-config-{{ current_date.stdout }}.txt"
