---
- name: Test Ping to IOS XR Device
  hosts: cisco
  gather_facts: no
  environment:
    ANSIBLE_LIBRARY: /usr/share/ansible/plugins/modules
  vars:
    ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD: True
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Ping a remote host from IOS XR device
      iosxr_command:
        commands:
          - ping 192.168.33.1
      register: ping_output

    - name: Display ping result
      debug:
        var: ping_output.stdout
    
    
    

