---
- name: Test Ping to IOS XR Device
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Ping a remote host from IOS XR device
      iosxr_command:
        commands:
          - ping 10.0.16.251
      register: ping_output

    - name: Display ping result
      debug:
        var: ping_output.stdout
    
    
    

