---
- name: Configure IOS XR interface with backup, validate, commit/rollback
  hosts: cisco
  gather_facts: no
  connection: network_cli
  vars:
    backup_path: "/tmp/ansible_backups/{{ inventory_hostname }}-running-config.backup"

  tasks:

    - name: Backup running config
      iosxr_command:
        commands:
          - show running-config
      register: running_config

    - name: Save backup config to control node
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "{{ backup_path }}"
      delegate_to: localhost

    - name: Load candidate config (do not commit yet)
      iosxr_config:
        lines:
          - interface GigabitEthernet0/0/0/0
          - description test
        commit: no
        rollback: yes
      register: candidate_result

    - name: Validate candidate config
      iosxr_command:
        commands:
          - commit validate
      register: validation_result
      failed_when: "'Commit failed' in validation_result.stdout[0]"

    - name: Commit config if validation passed
      iosxr_config:
        commit: yes
      when: validation_result is succeeded

    - name: Rollback config if validation failed
      iosxr_config:
        rollback: yes
      when: validation_result is failed
