---
- name: Backup, validate and apply interface description on IOS XR
  hosts: cisco
  gather_facts: no
  connection: network_cli
  become: yes

  vars:
    backup_dir: /tmp/ansible_backups
    backup_file: "{{ backup_dir }}/{{ inventory_hostname }}_running-config_{{ ansible_date_time.iso8601_basic_short }}.cfg"

  tasks:

    - name: Ensure backup directory exists on control node
      delegate_to: localhost
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup running config from device to control node
      iosxr_command:
        commands:
          - show running-config
      register: running_config

    - name: Save running config backup on control node
      delegate_to: localhost
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "{{ backup_file }}"

    - name: Configure interface description GigabitEthernet0/0/0/0 to "test" (candidate config)
      iosxr_config:
        lines:
          - interface GigabitEthernet0/0/0/0
          - description test
        diff_against: running
        diff_ignore_lines:
          - '.*timestamp.*'    # ignore lines like timestamps
        commit: no
        rollback: yes
      register: candidate_result

    - name: Validate candidate config
      iosxr_command:
        commands:
          - commit validate
      register: validation_result
      failed_when: "'Commit failed' in validation_result.stdout[0]"

    - name: Commit config if validation passed
      iosxr_commit:
        comment: "Set interface description GigabitEthernet0/0/0/0 to test"
      when: validation_result is succeeded

    - name: Rollback config if validation failed
      iosxr_commit:
        rollback: yes
      when: validation_result is failed
