---
- name: Safely change IOS XR interface description
  hosts: cisco
  gather_facts: no
  connection: network_cli
  vars:
    backup_dir: "/tmp/ansible_backups"
    interface_name: "GigabitEthernet0/0/0/0"
    new_description: "test"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  tasks:

  - name: Ensure backup directory exists
    delegate_to: localhost
    file:
      path: "{{ backup_dir }}"
      state: directory
      mode: '0777'

  - name: Backup current running config
    iosxr_command:
      commands: "show running-config"
    register: running_config

  - name: Save config backup to file
    delegate_to: localhost
    copy:
      content: "{{ running_config.stdout[0] }}"
      dest: "{{ backup_dir }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"

  - name: Load candidate config (not committed yet)
    iosxr_config:
      lines:
        - "description {{ new_description }}"
      parents: "interface {{ interface_name }}"
      comment: "Changing interface description"

  - name: Validate candidate config
    iosxr_command:
      commands: "show configuration failed"
    register: validation_result

  - name: Fail if config has validation errors
    fail:
      msg: "Validation failed. Aborting commit.\nDetails: {{ validation_result.stdout[0] }}"
    when: validation_result.stdout[0] != ""

  - name: Manually commit candidate config
    iosxr_command:
      commands: "commit"
