---
- name: Test Ping to IOS XR Device testtttttttt
  hosts: procisco
  gather_facts: no
  connection: network_cli
  vars:
    ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD: True
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Ping a remote host from IOS 
      iosxr_command:
        commands:
          - ping 10.0.16.251
      register: ping_output

    - name: Display ping result
      debug:
        var: ping_output.stdout

