---
- name: Test Ping to IOS XR Device
  hosts: procisco
  gather_facts: no
  vars:
    ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD: True

  tasks:
    - name: Ping a remote host from IOS 
      iosxr_command:
        commands:
          - ping 10.0.16.251
      register: ping_output

    - name: Display ping result
      debug:
        var: ping_output.stdout

